# Introduction to Python

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## Basic operations

In [2]:
#divison
5/8

0.625

In [3]:
#addition
7+10

17

In [4]:
#substraction
9-5

4

In [5]:
#product
3*5

15

In [6]:
#modulo
18%7

4

In [7]:
#exponentiation
4**2

16

## Variables and types

In [8]:
#int
s = 10
s

10

In [9]:
#float
t = 10.5
t

10.5

In [10]:
#string
e = 'maybe'
e

'maybe'

In [11]:
#boolean
y = True
y

True

In [12]:
#type of a variable
type(y)

bool

In [13]:
#change type of variable
l = str(s)
type(l)

str

## Python Lists

In [14]:
#this is a list data structure (it might contain different type of data)
fs = ['circle', 2, True]
fs

['circle', 2, True]

In [15]:
#list of lists
a = [[3,2],[2,1,2]]
a

[[3, 2], [2, 1, 2]]

In [16]:
#index in a list (negative index goes backwards)
z = [0,1,2]
z[2] == z[-1]

True

In [17]:
#useful notation to slice a list (my_list[start:end]) the end is not included
z[0:2]

[0, 1]

In [18]:
#semicolon means from the fisrt data or from the last one
z[:2]

[0, 1]

In [19]:
#subsetting list of lists (first is the index of the row and second is index of the column)
a[0][1]

2

In [20]:
#replacing elements
z[0] = 7
z

[7, 1, 2]

In [21]:
z[1:] = [5,9]
z

[7, 5, 9]

In [22]:
#addition operator in list concatenates 
z = z + [6]
z

[7, 5, 9, 6]

In [23]:
#delete list elements
del(z[1])
z

[7, 9, 6]

In [24]:
#a copy of a list will point to the same instance of memory. 
t = z
t[0] = 5
z

[5, 9, 6]

In [25]:
#to make a real copy you need to be more explicit.
z = [7,9,6]
t = z[:]
t[0] = 5 
z

[7, 9, 6]

## Functions

In [26]:
#basic python functions
type(z)

list

In [27]:
print(z)

[7, 9, 6]


In [28]:
str(2)

'2'

In [29]:
bool(0)

False

In [30]:
int(5.26)

5

In [31]:
float(5)

5.0

In [37]:
#to know more about a build-in function of python
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [36]:
complex(2,9)

(2+9j)

In [38]:
#pop up a new window with the info of the function
?sorted

In [39]:
sorted(z)

[6, 7, 9]

## Methods

In [40]:
#methods are just functions associated to python objects
s = 'elemento'
s.upper()

'ELEMENTO'

In [41]:
s.count('e')

3

In [43]:
z

[7, 9, 6]

In [44]:
z.index(9)

1

In [45]:
z.count(8)

0

In [50]:
#add, remove and reverse elements in a list
z.append(2)
z

[7, 9, 6, 2]

In [52]:
z.remove(7)
z

[9, 6, 2]

In [55]:
z.reverse()
z

[2, 6, 9]

## Packages

In [56]:
#packages are libraries with useful functions and methods
import math as ma
ma.pi

3.141592653589793

In [57]:
#specify which function you want to use
from math import pi
pi

3.141592653589793

## Numpy

In [58]:
#numpy is a library for math manipulation with lists (numeric python)
import numpy as np
np_z = np.array(z)
np_z

array([2, 6, 9])

In [59]:
#this will not happen in a list
np_z*2

array([ 4, 12, 18])

In [63]:
#here the addition symbol has a different purpose
np_z = np_z + np_z
np_z

array([ 8, 24, 36])

In [64]:
#filter by boolean conditions
v = np_z < 25
v

array([ True,  True, False])

In [65]:
np_z[v]

array([ 8, 24])

In [68]:
#numpy arrays cannot contain different types of data (type coercion)
np.array([2, s])

array(['2', 'elemento'], dtype='<U21')

In [69]:
f = np.array([[1,2],[3,4]])
f.shape

(2, 2)

In [72]:
#to access ND numpy arrays you do not need two [][], just before the comma goes the rows, and after the comma goes the columns
ñ = f[:,1]
ñ

array([2, 4])

In [73]:
ñ + [10,10]

array([12, 14])

In [74]:
#mean and median as methods of numpy
np.mean(f)

2.5

In [75]:
np.median(f)

2.5

In [76]:
np.corrcoef(f)

array([[1., 1.],
       [1., 1.]])

In [77]:
np.std(f)

1.118033988749895